fields:
    # Header
    create_date: datetime=now()
    create_ip: ip=clientIP()
    create_user_id: ref=userID()

    name: string(10, 250)
    key: string(10, 50)
    learning_category_id: ref(learning-category)
    valuable: boolean=false
