fields:
    # Header
    create_date: datetime=now()
    create_ip: ip=clientIP()
    create_user_id: ref=userID()

    firstname: string(2, 30)
    lastname: string(2, 50)
    role: enum(App\Entity\Person::getAllRoles)[nullable]

indexes:
    - UNIQUE(firstname, lastname)
