fields:
    # Header
    create_date: datetime=now()
    create_ip: ip=clientIP()
    create_user_id: ref=userID()

    update_date: datetime=now()
    pupil_id: ref(person)
    skill_id: ref(learning-skill)
    learning_sheet_id: ref(learning-sheet) # Shortcut
    value: string[nullable] # DEPRECATED : Should be null, use
    active_value_id: ref(pupil-skill-value)[nullable]

indexes:
    - UNIQUE(pupil_id, skill_id)
