fields:
    # Header
    create_date: datetime=now()
    create_ip: ip=clientIP()
    create_user_id: ref=userID()

    name: string(2, 50)
    level: enum(App\Entity\SchoolClass::getAllLevels)[nullable]
    year: integer(2020, 3000)
    teacher_id: ref(person)
    openDate: date
    enabled: boolean=true
