# User descriptor

fields:

    # Header
    create_date: datetime=now()
    create_ip: ip=clientIP()
    create_user_id: ref=userID()
    login_date: datetime[nullable]
    login_ip: ip[nullable]
    activity_date: datetime[nullable]
    activity_ip: ip[nullable]
    activation_date: datetime[nullable]
    activation_ip: ip[nullable]

    # Account
    email: email[nullable]
    password: password[nullable]
    fullname: string(4,30)
    published: boolean=true
    person_id: ref(person)=0

    # System infos
    accesslevel: natural(999)=0
    recovery_code: string(30)[nullable]
    recovery_date: datetime[nullable]
    activation_code: string(30)[nullable]s

indexes:
    - UNIQUE(email)
